### PR TITLE
Add tests for issue apis

### PR DESCRIPTION
**Pull request by aswinmprabhu**
#10

### CODE REVIEW

**Comment by alexdor** [comment]
When I try to run the test with buffalo test I don’t see this test running, am I doing smth wrong?

**Comment by aswinmprabhu** [comment]
You are not seeing them because they are passing. 
For example if you run `buffalo test -m  "Test_IssuesResource_Show"`, you will see that all tests in that particular suite pass. That's because only the Issue show function is being tested and it passed.

**Comment by aswinmprabhu** [comment]
@alexdor Did it work ? :)

**Review by alexdor — APPROVED** [review]

**Comment by alexdor** [comment]
Yep :)

**Pull request merged**
